### ISSUE TITLE
Refactoring Convolution Filtering

### ISSUE THREAD

**Issue by PritK99** [SRA-VJTI/Pixels_Seminar#120]
The code ```4_convolutions_filtering``` covers the following features:
* Naive Convolutions
* Convolutions using OpenCV
* Separable Convolutions
* Benchmarking for each of the above

This issue involves refactoring the provided convolution code into three separate files, each focusing on a specific aspect of convolution operations and creating a separate folder for benchmarking the results of each file. The goal is to is to enhance code modularity, readability, and maintainability by isolating different functionalities into distinct files. This would further reduce the complexity while understanding the code.
Benchmarking can be used solely for displaying the results and comparing the efficiency of different convolution approaches during the seminar. The code for benchmarking can be kept optional to explore.

**Comment by SuperChamp234** [comment]
Issue solved by #123 thanks to @AryanNanda17 !
