### ISSUE TITLE
Port to C++: Morphological Transformation.

### ISSUE THREAD

**Issue by amanchhaparia** [SRA-VJTI/Pixels_Seminar#50]
**Is your feature request related to a problem? Please describe.**
Current implementation of Morphological Transformation is in Python, it is needed to be ported in to C++ as discussed in this [thread](https://github.com/SRA-VJTI/Pixels_Seminar/issues/47).

**Describe the solution you'd like**

- Create a .cpp file performing morphological transformation by using necessary OpenCV C++ API.
- Create a Makefile to compile and build the executable.
- Create a `Readme.md` which contains the detailed explanation of the content similiar to jupyter notebook notes earlier, should contain the instructions to build and execute the code.

**Comment by Ris-Bali** [comment]
I would like to work on this issue
