### ISSUE TITLE
Port to C++: Blob Detection

### ISSUE THREAD

**Issue by amanchhaparia** [SRA-VJTI/Pixels_Seminar#51]
**Is your feature request related to a problem? Please describe.**
Current Blob Detection algorithm is implemented using Python, need to port to C++, as discussed in this [thread](https://github.com/SRA-VJTI/Pixels_Seminar/issues/47)

**Describe the solution you'd like**

- Implement the blob detection using the necessary OpenCV C++ API.
- Blob detection should have a option to run on webcam or on video depending on the argument provided while executing objectfile.
- Add a Makefile to compile and build a executable.
- Add a `Readme.md` explaining the algorithm in detail and should also contain the instruction for running the executable.

**Comment by toshan-luktuke** [comment]
I'll work on this part
