### ISSUE TITLE
Port to C++ : Convolution and Filtering

### ISSUE THREAD

**Issue by meshtag** [SRA-VJTI/Pixels_Seminar#52]
**Is your feature request related to a problem? Please describe.**
Current implementation of convolution is in Python. As discussed in [this](https://github.com/SRA-VJTI/Pixels_Seminar/issues/47) thread, we need to port it (1D, 2D and separable convolution) to C++. 

**Describe the solution you'd like**
 - Add a naive (using `for` loops by hand) as wells as proper (using native `OpenCV` API) implementation in C++. 
 - Add a `makefile` to compile and build related executable(s).
 - Maintain a `.md` file for theoretical part.
 - (Optional) We might as well benchmark (using `Google benchmarks`) both implementations (Naive `for` loops vs `OpenCV` 's implementation) to give students a fair idea about the optimization provided by `OpenCV`. We can have a discussion on this point once all other tasks are complete.

**Comment by shahpratham** [comment]
I would like to work on this

**Comment by aPR0T0** [comment]
I would like to work on this

**Comment by aPR0T0** [comment]
@amanchhaparia should we use google benchmark for benchmarking or the current chrono implementation is okay?
