### ISSUE TITLE
Port to C++ : OpenCV overview

### ISSUE THREAD

**Issue by meshtag** [SRA-VJTI/Pixels_Seminar#54]
**Is your feature request related to a problem? Please describe.**
We have a section covering some important introduction topics from `OpenCV`. This section covers all of them in Python atm, as discussed in [thread](https://github.com/SRA-VJTI/Pixels_Seminar/issues/47) thread, we need to port it to C++.

**Describe the solution you'd like**
 - Convert all relevant programs in [this](https://github.com/SRA-VJTI/Pixels_Seminar/blob/main/3_cv_basics/5_opencv_overview.ipynb) file to their equivalent C++ versions using `OpenCV`'s native API wherever required. 
 - Add theory related to `OpenCV`'s C++ APIs in accordance with current Python APIs present inside the above mentioned file. 
 - Create a `makefile` to build and compile related executable(s).
 - Maintain a `.md` file for theoretical part (and depicting expected results) as well.

**Comment by sarrah-basta** [comment]
I'll work on this part and the programs in the file prior to masking as that is covered in a seperate issue

**Comment by Om-Doiphode** [comment]
I have issued a PR [here](https://github.com/SRA-VJTI/Pixels_Seminar/pull/69#issue-1591985336)
