### ISSUE TITLE
Port to C++: Masking

### ISSUE THREAD

**Issue by amanchhaparia** [SRA-VJTI/Pixels_Seminar#55]
**Is your feature request related to a problem? Please describe.**
Current contents and implementation of masking is in Python. As discussed in the [thread](https://github.com/SRA-VJTI/Pixels_Seminar/issues/47), it is needs to port to C++.

**Describe the solution you'd like**

- Implement the masking operations using necessary OpenCV C++ API methods.
- Create `Makefile` to compile and build the executables. 
- Add a `.md` file explaining the concepts and instructions for running the executables.

**Comment by Dhruv454000** [comment]
I would like to work on this issue.

**Comment by notad22** [comment]
I would like to port this
