### ISSUE TITLE
Add Content: C++ basic concepts for seminar.

### ISSUE THREAD

**Issue by amanchhaparia** [SRA-VJTI/Pixels_Seminar#57]
**Is your feature request related to a problem? Please describe.**
Since the seminar is being ported to C++ as discussed in this [thread](https://github.com/SRA-VJTI/Pixels_Seminar/issues/47), it is important to teach some important C++ concepts.

**Describe the solution you'd like**

- Some advance concepts of C++ like handling 2D arrays/vector, pointer etc.

_Note: Content is not finalised and open for discussion._

**Comment by Neel-Shah-29** [comment]
I would like to work on this issue.
