### ISSUE TITLE
Add Content: Build Systems

### ISSUE THREAD

**Issue by amanchhaparia** [SRA-VJTI/Pixels_Seminar#58]
**Is your feature request related to a problem? Please describe.**
As discussed in the [thread](https://github.com/SRA-VJTI/Pixels_Seminar/issues/47), Concepts of Build System should be added.

**Describe the solution you'd like**

- Content should be added for manual creating and linking the object files.
- Importance of build systems.
- Add the contents for Makefile.
- Add contents for Cmake.

**Additional context**
Can refer from here: [Embedded Study Group Week 2](https://github.com/SRA-VJTI/embedded-systems-study-group/blob/master/week2/week2.md).

_Note: Content is not finalised and open for discussion._

**Comment by SuperChamp234** [comment]
I would like to work on this issue, along with @PritK99

**Comment by RISHI27-dot** [comment]
Hello @SuperChamp234 and @PritK99. Have you started workign on this issue?

**Comment by SuperChamp234** [comment]
Yes we are working on it, just recently added the `Makefile` for the whole project. Will be adding content now, explaining what a Makefile is, general Makefile Structure and some example Makefile writing exercises.
