### ISSUE TITLE
Add Content: Image Storing Formats.

### ISSUE THREAD

**Issue by amanchhaparia** [SRA-VJTI/Pixels_Seminar#59]
**Is your feature request related to a problem? Please describe.**
As discussed in the [thread](https://github.com/SRA-VJTI/Pixels_Seminar/issues/47), It is important to have a familiarity of how images are store.

**Describe the solution you'd like**

- Add the theory of basic image storing formats such as `.bmp`, `.tiff`, ` .jpg`, `png` etc.
- Implement a `.cpp` file on how image can be read from the bmp format.
    - Consider only 8 bit grayscale BitMap image (Since they are easy to read and contains only 2D form of data).
    - Use simple posix read() api to read the image bitmap file.
    - Directly storing the values of various attributes of image in struct is suggested.
- A similar example can be added to demonstrate how to edit/write a grayscale bitmap image.
- Add a `Makefile` to compile and build the executable.
- Add a `.md` file explaining the theory and instructions to build and run the executables. 

_Note: Content is not finalised and open for discussion._

**Comment by gautam-dev-maker** [comment]
For reading and writing of images from scratch it is recommended to go with Grayscale (8bit) BMP image, since it consists of only 2D array data.

**Comment by amanchhaparia** [comment]
@gautam-dev-maker , The goals of this issue have been updated as per your suggestion!
If there are any other suggestions, feel free to share.

**Comment by ChinmayMundane** [comment]
I would like to work on this issue.
